### ISSUE TITLE
Do lecture dry run to test software

### ISSUE THREAD

**Issue by CCheCastaldo** [CCheCastaldo/BayesianShortCourse#6]

**Comment by nthobbs50** [comment]
@CCheCastaldo @mbcolli 

Here are some things we need to test during our dry run.  Please add as you see fit.

1) Class responds by putting an answer, e.g., Derive Bayes Theorem, on Jamboard
2) Using dual monitors to see class while lecturing.  Leave microphones and videos on.
3) Using Goodnotes during lecture.
4) Random breakout rooms during lecture
5) Doing recordings (with pause?)
5) Slack group work -- this will require sending invitations to all of our test participants.

**Comment by CCheCastaldo** [comment]
done
